### ISSUE TITLE
Unable to make this work.

### ISSUE THREAD

**Issue by ghost** [Luukuton/MecabUnidic#2]
Hey! I'm running Manjaro. Is there something else that needs to be done after installing this addon? I don't see any new options in Morphman (no new option to select this morphemizer). I do have installed the Mecab addon which from anki web and that one works.

**Comment by CrescentKohana** [comment]
It seems that on Linux there was a problem with the name of the binary `mecab`. I have renamed it to `mecab.lin` which should have fixed the problem. Tested that everything works on Arch Linux.

Also, please disable/remove the original MeCab plugin first as it can conflict with this one.

[Download the latest release here](https://github.com/Luukuton/MecabUnidic/releases/tag/v1.2.1)

**Comment by ghost** [comment]
This fixed the error and everything's working excellent now!
